server:
  port: 8094

spring:
  application:
    name: auth-user

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # Use validate for safety in production
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      INDENT_OUTPUT: false

logging:
  level:
    root: WARN
    com.authuser: INFO
    org.springframework.security: WARN

cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST"
  
  
consent:
  service:
    url: http://consent-service:8096/api/v1
