server:
  port: 8094

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-wgk04dj5v68sbhre.us.auth0.com/
  application:
    name: auth-user


logging:
  level:
    root: INFO
    com.authuser: DEBUG
    org.springframework.security: DEBUG
    

    
    
consent:
  service:
    url: http://localhost:8096/api/v1
    
    
auth0:
  domain: https://dev-wgk04dj5v68sbhre.us.auth0.com
  audience: https://mockbank/api
  mgmt:
     client-id: 7m9h4UQsjOeVom5ysSt0t3TFLRgibBkT
     client-secret: XXXXXXX
     audience: https://dev-wgk04dj5v68sbhre.us.auth0.com/api/v2/